# Generated by Django 4.0.6 on 2022-08-17 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=200)),
                ('categoryDescription', models.CharField(max_length=200)),
                ('condition', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('productDescription', models.CharField(max_length=200)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condition', models.BooleanField(default=True, null=True)),
                ('categorieId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProductsCategory', to='products.categories')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
