# Generated by Django 4.0.6 on 2022-08-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('condition', models.BooleanField(default=True, null=True)),
                ('productDescription', models.CharField(max_length=200)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
