# Generated by Django 4.0.6 on 2022-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productImage',
            field=models.TextField(default='https://www.google.com'),
        ),
    ]
