# Generated by Django 4.0.6 on 2022-08-18 11:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_products_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='condition',
            new_name='categoryStatus',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='condition',
            new_name='productStatus',
        ),
        migrations.AlterField(
            model_name='products',
            name='categorieId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('purchaseDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('purchaseDetailAmount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'purchase_detail',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchaseId', models.AutoField(primary_key=True, serialize=False)),
                ('purchaseCreated', models.DateTimeField(default=datetime.datetime(2022, 8, 18, 12, 3, 29, 628986))),
                ('purchaseStatus', models.BooleanField(default=True)),
                ('purchaseTotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
    ]
